version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/kc
      - KC_DB_USERNAME=kc
      - KC_DB_PASSWORD=keycloak
    command: start-dev
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=keycloak
      - MYSQL_DATABASE=kc
      - MYSQL_USER=kc
      - MYSQL_PASSWORD=keycloak
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10